// Generated by CoffeeScript 1.6.2
(function() {
  var HOUR, METERS_IN_A_MILE, MINUTE, conversions, moment, viewHelpers;

  moment = require('moment');

  METERS_IN_A_MILE = 1609.344;

  HOUR = 3600;

  MINUTE = 60;

  conversions = {
    metersToMi: function(meters) {
      return (meters / METERS_IN_A_MILE).toFixed(2);
    },
    secondsToHms: function(seconds) {
      var hours, minutes;

      hours = Math.floor(seconds / HOUR);
      seconds -= hours * HOUR;
      minutes = Math.floor(seconds / MINUTE);
      seconds -= minutes * MINUTE;
      return [hours, minutes, Math.floor(seconds)].join(':');
    },
    pace: function(meters, seconds) {
      var miles, minutes;

      minutes = seconds / 60;
      miles = meters / METERS_IN_A_MILE;
      return (minutes / miles).toFixed(2);
    }
  };

  viewHelpers = {
    formatDateTime: function(rkTimeString) {
      return moment(rkTimeString).format('MMM d, YYYY (ddd) @ h:mmA');
    },
    formatTimeDuration: function(rkTimeString, seconds) {
      var end, start;

      start = moment(rkTimeString);
      end = start.clone().add('seconds', seconds);
      return start.format('hh:mmA') + ' - ' + end.format('hh:mmA');
    },
    cellToolTip: function(act) {
      var dist, dur, tips;

      dist = act['total_distance'];
      dur = act['duration'];
      tips = [];
      tips.push("" + (conversions.metersToMi(dist)) + " miles (" + (conversions.pace(dist, dur)) + " min/mi)");
      tips.push(viewHelpers.formatTimeDuration(act['start_time'], act['duration']));
      return tips.join('<br/>');
    }
  };

  exports.helpers = {
    metersToMi: conversions.metersToMi,
    secondsToHms: conversions.secondsToHms,
    formatDateTime: viewHelpers.formatDateTime,
    formatTime: viewHelpers.formatTime,
    cellToolTip: viewHelpers.cellToolTip,
    pace: conversions.pace
  };

}).call(this);
